version: "3"
services:
  traefik:
    image: "traefik:v2.0"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web-secure.address=:443 #Declares the web-secure entrypoint in Traefik
      - --providers.docker=true
      - --providers.file.directory=/configuration/
      - --providers.file.watch=true
    ports:
      - "80:80"
      - "443:443" #Docker sends requests on port 443 to Traefik on port 443
    volumes: 
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "/home/abdullah/personal/github-projects/traefik_labs/self_signed_cert_install/configuration:/configuration"
  
  my-app:
    image: containous/whoami:v1.3.0
    labels: 
      - "traefik.http.routers.my-app.rule=Host(`localhost`)"
      - "traefik.http.routers.my-app.tls=true"